# Generated by Django 3.2 on 2026-07-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20260511_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatFamilyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('parent', 'Родитель'), ('guardian', 'Опекун')], default='parent', max_length=16)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='cats.cat')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='cats.cat')),
            ],
            options={
                'ordering': ('parent__name', 'child__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='catfamilyrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_cat_parent_child'),
        ),
    ]
